<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container69zrn7t\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container69zrn7t/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container69zrn7t.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container69zrn7t\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container69zrn7t\appDevDebugProjectContainer(array(
    'container.build_hash' => '69zrn7t',
    'container.build_id' => 'e5b7a68e',
    'container.build_time' => 1530691458,
), __DIR__.\DIRECTORY_SEPARATOR.'Container69zrn7t');
